# Generated by Django 3.1.7 on 2021-04-05 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60)),
                ('describtion', models.TextField(max_length=60)),
                ('tumbnail', models.ImageField(upload_to='image')),
                ('publish', models.TimeField(default=django.utils.timezone.now)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'published')], max_length=1)),
            ],
        ),
    ]
